version: '3.9'

services:
  smart-brain-api:
    container_name: "backend"
#    image: node:14.17.0
    command: npm start
    build: ./

    working_dir: /usr/src/smart-brain-api
    ports:
      - "3000:3000"




